asbamboo\openpay\model\tradePayClob\TradePayClobEntity:
  type: mappedSuperclass
  table: t_api_trade_pay_clob
  id:
    seq:
      type: integer
      generator:
        strategy: AUTO
  fields:
    in_trade_no:
      unique: true
      type: string
      length: 32
      nullable: false
      options:
        default: ''
    app_pay_json: 
      type: text
      nullable: false
      options:
        default: '{}'
    third_part:
      type: text
      nullable: false
      options:
        default: '{}'