asbamboo\openpay\model\tradePayThirdPart\TradePayThirdPartEntity:
  type: entity
  table: t_api_trade_pay_third_part
  id:
    seq:
      type: integer
      generator:
        strategy: AUTO
  fields:
    in_trade_no:
      unique: true
      type: string
      length: 32
      nullable: false
      options:
        default: ''
    send_data:
      type: text
      nullable: false
      options:
        default: '[]'